import { StyleSheet } from 'react-native';
import { global } from '../../styles/globals';

export const styles = StyleSheet.create({
  plantImage__container: {
    width: 120,
    height: '80%',
    top: '10%',
    borderRadius: 20,
    left: '5%',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    opacity: 0.7,
  },
  plantImage__container__small: {
    width: 60,
    height: 75,
    top: '10%',
    borderRadius: 20,
    left: '5%',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    opacity: 0.7,
  },
  plantImage__topLeftShadow: {
    position: 'absolute',
    top: -65,
    left: -65,
    width: 130,
    height: 130,
    backgroundColor: global.color.primary.backgroundColor,
    opacity: 0.1,
    borderRadius: 25,
    transform: [{ rotate: '45deg' }],
  },
  plantImage__bottomRightShadow: {
    position: 'absolute',
    bottom: -70,
    right: -75,
    width: 130,
    height: 130,
    backgroundColor: global.color.primary.backgroundColor,
    opacity: 0.1,
    borderRadius: 25,
    transform: [{ rotate: '45deg' }],
  },
  plantImage__image: {
    width: '80%',
    height: '80%',
    overflow: 'hidden',
    borderRadius: 20,
  },
  plantInformation__container: {
    position: 'absolute',
    width: '60%',
    right: '0%',
    top: '27%',
    height: '100%',
  },
  plantInformation__plantName: {
    fontSize: 25,
    fontWeight: 'bold',
    color: global.color.primary.backgroundColor,
  },
  plantInformation__plantDescription: {
    fontSize: 12,
    color: global.color.primary.backgroundColor,
    fontStyle: 'italic',
  },
  plantWatering__container: {
    position: 'absolute',
    top: '6%',
    right: 0,
    width: '18%',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.9,
  },
  expandedCard__container: {
    position: 'absolute',
    bottom: 0,
    left: '50%',
    width: 50,
    transform: [{ translateX: -20 }],
    zIndex: 2,
  },

  overlay_container: {
    position: 'absolute',
    top: 0,
    left: '2.2%',
    width: '102%',
    height: '100%',
    borderRadius: 20,
    backgroundColor: 'white',
    zIndex: 1,
    shadowColor: 'black',
  },
  showPlantButton__container: {
    position: 'absolute',
    bottom: 20,
    right: 25,
    width: 50,
    zIndex: 2,
  },
  showPlantButton__button: {
    width: 55,
    height: 40,
    borderRadius: 10,
    backgroundColor: global.color.secondary.color,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0.7,
  },
});
