import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  puscica: {
    position: 'absolute',
    left: 10,
    top: 10,
    marginTop: '10%',
    marginLeft: 11,
  },
  input: {
    borderBottomWidth: 1,
    borderBottomColor: '#648983',
    fontSize: 16,
    paddingVertical: 2,
    marginVertical: 20,
    paddingHorizontal: 5,
    color: '#648983',
    width: '70%',
    marginBottom: '5%',
  },
  recover: {
    color: '#b6c9c5',
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: '10%',
    marginTop: '40%',
  },
  icon: {
    borderBottomWidth: 1,
    borderBottomColor: '#648983',
    paddingVertical: 3,
    marginVertical: 20,
    paddingHorizontal: 5,
  },
  container: {
    flex: 1,
    backgroundColor: '#134b3f',
    alignItems: 'center',
  },
  button1: {
    color: 'white',
    backgroundColor: '#30312c',
    width: '70%',
    height: 45,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '10%',
  },
  buttonText: {
    textTransform: 'uppercase',
    fontSize: 10,
    color: 'white',
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
