import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  leftContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  rightContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  middleContainer: {
    alignItems: 'center',
  },
  text: {
    fontSize: 16,
    color: '#648983',
  },
  text1: {
    color: '#134a3e',
    fontSize: 12,
    marginBottom: 4,
  },
  text2: {
    fontSize: 16,
    marginBottom: 8,
  },
  text3: {
    fontSize: 16,
    marginBottom: 16,
    marginLeft: 8,
    marginRight: 8,
  },
  amount: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  puscica: {
    position: 'absolute',
    left: 10,
    top: 10,
    marginTop: '10%',
    marginLeft: 11,
  },
  edit: {
    position: 'absolute',
    right: 10,
    top: 10,
    marginTop: '10%',
    marginLeft: '1%',
  },
  container: {
    flex: 1,
    alignItems: 'center',
  },
  ime: {
    position: 'absolute',
    top: 10,
    fontSize: 20,
    marginTop: '10%',
    fontWeight: 'bold',
  },
  image: {
    width: '70%',
    aspectRatio: 1,
    marginBottom: '5%',
    borderRadius: 50,
    alignSelf: 'center',
  },
  input: {
    borderBottomWidth: 1,
    borderBottomColor: '#648983',
    fontSize: 16,
    color: 'black',
    width: '90%',
    marginBottom: 10,
  },
  input2: {
    borderBottomWidth: 1,
    borderBottomColor: '#648983',
    fontSize: 16,
    color: 'black',
    width: '40%',
    marginBottom: 4,
  },
  icon: {
    marginRight: 10,
  },
  buttonContainer: {
    backgroundColor: '#B00020',
    height: 45,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '10%',
    marginTop: '2%',
    display: 'flex',
    justifyItems: 'center',
  },
  button: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    textTransform: 'uppercase',
    fontSize: 10,
    color: 'white',
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },

  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    backgroundColor: 'rgba(205,227,214,0.9)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  modalText: {
    flex: 1,
    marginRight: 8,
    paddingVertical: 10,
    borderRadius: 10,
    padding: 10,
  },
});
